openapi: 3.0.1
info:
  title: Symphony
  description: ''
  version: '1.0'
servers:
  - url: https://symphony-test.azure-api.net
paths:
  /v1alpha2/greetings:
    get:
      summary: greetings
      operationId: greetings
      responses:
        '200':
          description: 
  /v1alpha2/users/auth:
    post:
      summary: Auth
      operationId: auth
      responses:
        '200':
          description: 
    options:
      summary: Users auth option
      operationId: users-auth-option
      responses:
        '200':
          description: 
  /v1alpha2/solutions:
    get:
      summary: Get solutions
      operationId: get-solutions
      parameters:
        - name: path
          in: query
          schema:
            type: string
        - name: doc-type
          in: query
          schema:
            type: string
      responses:
        '200':
          description: 
    options:
      summary: Solutions options
      operationId: solutions-options
      responses:
        '200':
          description: 
  '/v1alpha2/solutions/{name}':
    get:
      summary: Get solution
      operationId: get-solution
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: ''
        - name: path
          in: query
          schema:
            type: string
        - name: doc-type
          in: query
          schema:
            type: string
      responses:
        '200':
          description: 
    delete:
      summary: Delete solution
      operationId: delete-solution
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: ''
      responses:
        '200':
          description: 
    post:
      summary: Solution creation/update
      operationId: solution-creation-update
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: ''
        - name: embed-type
          in: query
          schema:
            type: string
        - name: embed-component
          in: query
          schema:
            type: string
        - name: embed-property
          in: query
          schema:
            type: string
      responses:
        '200':
          description: 
    options:
      summary: Solution options
      operationId: solution-options
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: ''
        - name: embed-type
          in: query
          schema:
            type: string
        - name: embed-component
          in: query
          schema:
            type: string
        - name: embed-property
          in: query
          schema:
            type: string
      responses:
        '200':
          description: 
  /v1alpha2/instances:
    get:
      summary: Get instances
      operationId: get-instances
      parameters:
        - name: path
          in: query
          schema:
            type: string
        - name: doc-type
          in: query
          schema:
            type: string
      responses:
        '200':
          description: 
    options:
      summary: Instances options
      operationId: instances-options
      responses:
        '200':
          description: 
  '/v1alpha2/instances/{name}':
    get:
      summary: Get instance
      operationId: get-instance
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: ''
        - name: path
          in: query
          schema:
            type: string
        - name: doc-type
          in: query
          schema:
            type: string
      responses:
        '200':
          description: 
    delete:
      summary: Delete instance
      operationId: delete-instance
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: ''
      responses:
        '200':
          description: 
    options:
      summary: Instance option
      operationId: instance-option
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: ''
        - name: solution
          in: query
          schema:
            type: string
        - name: target
          in: query
          schema:
            type: string
        - name: target-selector
          in: query
          schema:
            type: string
      responses:
        '200':
          description: 
    post:
      summary: Instance Create/update
      operationId: instance-create-update
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: ''
        - name: solution
          in: query
          schema:
            type: string
        - name: target
          in: query
          schema:
            type: string
        - name: target-selector
          in: query
          schema:
            type: string
      responses:
        '200':
          description: 
  /v1alpha2/targets/registry:
    get:
      summary: Get targets
      operationId: get-targets
      parameters:
        - name: path
          in: query
          schema:
            type: string
        - name: doc-type
          in: query
          schema:
            type: string
      responses:
        '200':
          description: 
    options:
      summary: Targets options
      operationId: targets-options
      parameters:
        - name: path
          in: query
          schema:
            type: string
        - name: doc-type
          in: query
          schema:
            type: string
      responses:
        '200':
          description: 
  '/v1alpha2/targets/registry/{name}':
    get:
      summary: Get target
      operationId: get-target
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: ''
        - name: path
          in: query
          schema:
            type: string
        - name: doc-type
          in: query
          schema:
            type: string
      responses:
        '200':
          description: 
    delete:
      summary: Delete target
      operationId: delete-target
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: ''
      responses:
        '200':
          description: 
    post:
      summary: Target creation/update
      operationId: target-creation-update
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: ''
        - name: with-binding
          in: query
          schema:
            type: string
      responses:
        '200':
          description: 
    options:
      summary: Target options
      operationId: target-options
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: ''
        - name: with-binding
          in: query
          schema:
            type: string
      responses:
        '200':
          description: 
  '/v1alpha2/targets/ping/{name}':
    get:
      summary: Target ping
      operationId: target-ping
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: ''
      responses:
        '200':
          description: 
  '/v1alpha2/targets/download/{doc-type}/{name}':
    get:
      summary: Target download
      operationId: target-download
      parameters:
        - name: doc-type
          in: path
          required: true
          schema:
            type: ''
        - name: name
          in: path
          required: true
          schema:
            type: ''
        - name: path
          in: query
          schema:
            type: string
      responses:
        '200':
          description: 
  '/v1alpha2/targets/status/{name}':
    put:
      summary: Target report state
      operationId: target-report-state
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: ''
      responses:
        '200':
          description: 
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]