apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-hook-role
  labels:
    app: symphony-api
rules:
- apiGroups: ["symphony.microsoft.com"] 
  resources: ["targets", "instances", "solutions"]
  verbs: ["get", "watch","list", "patch", "delete"]
