apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-hook-role
  labels:
    app: symphony-api
rules:
- apiGroups: ["symphony.microsoft.com"] 
  resources: ["targets", "instances", "solutions"]
  verbs: ["get", "watch","list", "patch", "delete"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["delete"]
  resourceNames: ["targets.symphony.microsoft.com", "instances.symphony.microsoft.com", "solutions.symphony.microsoft.com"]
