replicaCount: 1
image:
  repository: symphonycr.azurecr.io/gitops-service
  pullPolicy: IfNotPresent
  tag: "0.0.5"
  containerPort: 8080
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  port: 80
resources: {}
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
envFileContent: ""
ingress:
  enabled: true
  # className: addon-http-application-routing
  annotations: 
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: addon-http-application-routing
    cert-manager.io/cluster-issuer: letsencrypt
  hosts:
    - host: gitops.e718708818f943b3813b.eastus.aksapp.io
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: gitops-service
              port:
                number: 80
  tls: 
    - secretName: tls-secret
      hosts:
        - gitops.e718708818f943b3813b.eastus.aksapp.io