apiVersion: v2
name: symphony
description: A Helm chart for Symphony control plane
type: application
version: 0.44.0
appVersion: "0.44.0"
dependencies:
  - name: cert-manager
    version: "1.4.0"
    repository: "https://charts.jetstack.io"
