{{- if .Values.installServiceExt }}
apiVersion: v1
kind: Service
metadata:
  name: symphony-service-ext
  namespace: symphony-k8s-system
spec:
  selector:
    app: symphony-api
  externalTrafficPolicy: Local
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    name: http
  - protocol: TCP
    port: 8081
    targetPort: 8081
    name: https
  {{- end }}