apiVersion: apps/v1
kind: Deployment
metadata:
  name: symphony-api
  labels:
    app: symphony-api
  namespace: symphony-k8s-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: symphony-api
  template:
    metadata:
      labels:
        app: symphony-api
    spec:
      {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      serviceAccountName: pai-sp
      containers:
      - name: symphony-api
        securityContext: {{- toYaml .Values.securityContext | nindent 12 }}
        image: {{ .Values.paiImage.repository }}:{{ .Values.paiImage.tag }}
        imagePullPolicy: {{ .Values.paiImage.pullPolicy }}
        ports:
        - containerPort: 8080
        - containerPort: 8081
        env:          
          - name: "HELM_NAMESPACE"
            value: default
          - name: "CONFIG"
            value: /etc/symphony-api/config/symphony-api.json
        envFrom:
          - secretRef:
              name: {{ .Release.Name }}-auth
        volumeMounts:
        - name: symphony-api-config
          mountPath: /etc/symphony-api/config
      {{- if .Values.global.azure.identity.mSIAdapterYaml }}
      - name: msi-adapter
        env:
        - name: TOKEN_NAMESPACE
          value: symphony-k8s-system
        {{- .Values.global.azure.identity.mSIAdapterYaml | nindent 8 }}
      {{- end }}
      volumes:
        - name: symphony-api-config
          configMap:
            name: symphony-api-config