apiVersion: fabric.symphony/v1
kind: Target
metadata:
  name: sample-staged-k8s
spec:  
  topologies:
  - bindings:
    - role: instance
      provider: providers.target.staging
      config:
        targetName: "sample-staged-k8s"
        inCluster: "true"   