apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: instances.solution.symphony
  # Add in annotations for the resource provider.
  annotations:
    management.azure.com/providerName: Microsoft.Symphony
    management.azure.com/resourceType: instances
    management.azure.com/api-version: 2020-01-01-preview
spec:
  group: solution.symphony
  versions:
    - name: v1
      served: true
      storage: true
  scope: Namespaced
  names:
    kind: Instance
    listKind: InstanceList
    plural: instances
    singular: instance
  preserveUnknownFields: false
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          description: InstanceSpec defines the desired state of Instance
          properties:
            displayName: 
              type: string
            metadata:
              additionalProperties:
                type: string
              type: object
            parameters:
              additionalProperties:
                type: string
              type: object
            scope:
              type: string
            stage:
              type: string
            stages:
              items:
                properties:
                  arguments:
                    additionalProperties:
                      additionalProperties:
                        type: string
                      type: object
                    type: object
                  name:
                    type: string
                  pipelines:
                    items:
                      properties:
                        name:
                          type: string
                        parameters:
                          additionalProperties:
                            type: string
                          type: object
                        skill:
                          type: string
                      required:
                      - name
                      - skill
                      type: object
                    type: array
                  schedule:
                    type: string
                  solution:
                    type: string
                  target:
                    properties:
                      name:
                        type: string
                      selector:
                        additionalProperties:
                          type: string
                        type: object
                    type: object
                  topologies:
                    items:
                      properties:
                        bindings:
                          items:
                            properties:
                              config:
                                additionalProperties:
                                  type: string
                                type: object
                              provider:
                                type: string
                              role:
                                type: string
                            required:
                            - provider
                            - role
                            type: object
                          type: array
                        device:
                          type: string
                        selector:
                          additionalProperties:
                            type: string
                          type: object
                      type: object
                    type: array
                required:
                - name
                - solution
                type: object
              type: array
          required:
          - stages
          type: object