symphonyImage:
  repository: symphonycr.azurecr.io/symphony-k8s
  pullPolicy: Never
  tag: local
paiImage:
  repository: symphonycr.azurecr.io/symphony-api
  pullPolicy: Never
  tag: local
CUSTOM_VISION_KEY: "AAAA"
installServiceExt: false
global:
  azure:
    identity:
      enabled: false