apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: targets.fabric.symphony
  # Add in annotations for the resource provider.
  annotations:
    management.azure.com/providerName: Microsoft.Symphony
    management.azure.com/resourceType: targets
    management.azure.com/api-version: 2020-01-01-preview
spec:
  group: fabric.symphony
  versions:
    - name: v1
      served: true
      storage: true
  scope: Namespaced
  names:
    kind: Target
    listKind: TargetList
    plural: targets
    singular: target
  preserveUnknownFields: false
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          description: Target is the Schema for the targets API
          properties:
            components:
              items:
                properties:
                  constraints:
                    items:
                      description: 'NOTE: json tags are required.  Any new fields
                        you add must have json tags for the fields to be serialized.'
                      properties:
                        key:
                          type: string
                        operator:
                          type: string
                        qualifier:
                          type: string
                        value:
                          type: string
                        values:
                          items:
                            type: string
                          type: array
                      required:
                      - key
                      type: object
                    type: array
                  dependencies:
                    items:
                      type: string
                    type: array
                  metadata:
                    additionalProperties:
                      type: string
                    type: object
                  name:
                    type: string
                  propertiesHMM:
                    additionalProperties:
                      type: string
                    type: object
                  routes:
                    items:
                      properties:
                        filters:
                          items:
                            properties:
                              direction:
                                type: string
                              parameters:
                                additionalProperties:
                                  type: string
                                type: object
                              type:
                                type: string
                            required:
                            - direction
                            - type
                            type: object
                          type: array
                        metadata:
                          additionalProperties:
                            type: string
                          type: object
                        name:
                          type: string
                        route:
                          type: string
                      required:
                      - name
                      - route
                      type: object
                    type: array
                  skills:
                    items:
                      type: string
                    type: array
                  type:
                    type: string
                required:
                - name
                type: object
              type: array
            constraints:
              items:
                description: 'NOTE: json tags are required.  Any new fields you
                  add must have json tags for the fields to be serialized.'
                properties:
                  key:
                    type: string
                  operator:
                    type: string
                  qualifier:
                    type: string
                  value:
                    type: string
                  values:
                    items:
                      type: string
                    type: array
                required:
                - key
                type: object
              type: array
            displayName:
              type: string
            forceRedeploy:
              type: boolean
            metadata:
              additionalProperties:
                type: string
              type: object
            propertiesHMM:
              additionalProperties:
                type: string
              type: object
            topologies:
              items:
                properties:
                  bindings:
                    items:
                      properties:
                        config:
                          additionalProperties:
                            type: string
                          type: object
                        provider:
                          type: string
                        role:
                          type: string
                      required:
                      - provider
                      - role
                      type: object
                    type: array
                  device:
                    type: string
                  selector:
                    additionalProperties:
                      type: string
                    type: object
                type: object
              type: array
          type: object