# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  vmImage: ubuntu-22.04
  name: iots-saas-hosted-agents
  
variables:
  CI: true

steps:
- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'
- task: GoTool@0
  inputs:
    version: '1.20.3'
- task: HelmInstaller@0
  inputs:
    helmVersion: '3.11.0'
    installKubectl: true
    kubectlVersion: '1.18.6'
- task: Go@0
  inputs:
    command: 'custom'
    customCommand: 'install'
    arguments: 'github.com/magefile/mage@latest'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Set minikube home to working dir
      export MINIKUBE_HOME="$(pwd)/.minikube"
      echo "MINIKUBE_HOME: $MINIKUBE_HOME"

      # fail on errors
      set -e      
     
      # load up minikube
      
      pushd localenv
      $HOME/go/bin/mage SetupIntegrationTests
      popd
      
      # run integration tests
      # TODO add tests
      
      echo "DONE! exit: $?"