# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-22.04
  name: iots-saas-hosted-agents
  
variables:
  CI: true

steps:
- task: DockerInstaller@0
  displayName: Install Docker
  inputs:
    dockerVersion: '24.0.2'
- task: GoTool@0
  displayName: Use Go v1.20.3
  inputs:
    version: '1.20.3'
- task: HelmInstaller@0
  displayName: Install Helm
  inputs:
    helmVersion: '3.11.0'
    installKubectl: true
    kubectlVersion: '1.18.6'
- task: Go@0
  displayName: Install Mage
  inputs:
    command: 'custom'
    customCommand: 'install'
    arguments: 'github.com/magefile/mage@latest'
- task: Bash@3
  displayName: Run integration tests
  inputs:
    targetType: 'inline'
    script: |
      # Set minikube home to working dir
      export MINIKUBE_HOME="$(pwd)/.minikube"
      echo "MINIKUBE_HOME: $MINIKUBE_HOME"

      # Add mage to path
      export PATH=$HOME/go/bin:$PATH

      # fail on errors
      set -e      
     
      # load up minikube
      
      pushd localenv
      mage SetupIntegrationTests
      popd
      
      # run integration tests
      pushd test/integration
      mage Test
      
      echo "DONE! exit: $?"