apiVersion: fabric.symphony/v1
kind: Target
metadata:
  name: mac-book
spec:
  topologies:
  - bindings:  
    - role: instance
      provider: providers.target.proxy
      config:
        name: proxy
        serverUrl: "http://192.168.50.113:8098/v1alpha2/solution/"