# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
        
    - name: Set up custom GOPATH
      run: |
        mkdir -p /home/runner/go
        echo "export GOPATH=/home/runner/go" >> $HOME/.bashrc
        echo "export PATH=\$PATH:\$GOPATH/bin" >> $HOME/.bashrc
        source $HOME/.bashrc
          
    - name: Install make
      run: sudo apt-get update && sudo apt-get install -y build-essential
        
    - name: COA Vendor
      run: cd coa && go mod vendor
    
    - name: COA Test
      run: cd coa && go test -v ./...
      
    - name: API Vendor
      run: cd api && go mod vendor
      
    - name: API Build
      run: cd api && go build -v ./...

    - name: API Test
      run: cd api && go test -v ./...
  
    - name: K8s Vendor
      run: cd k8s && go mod vendor
    
    - name: K8s Build
      run: cd k8s && make build
      
    - name: K8s Test
      run: cd k8s && make test
      
